spring:
  application:
    name: kim-Eureka

server:
  port: 8761
eureka:
  instance:
    hostname: 192.168.75.137
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
