spring:
  application:
    name: kim-Eureka
  boot:
    admin:
      client:
        url: http://192.168.0.104:8084

server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.0.104
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/